version: '3.8'

services:
  bot_test:
    build:
      context: .
    container_name: bot_test
    volumes:
      - ./app:/app
      - /home/Bot_Server/DBGestionBot/:/DBGestionBot
    environment:
      - BOT_NAME=Bot_test
      - CHROME_PORT=4445
      - CHROME_HOST=bot_test_chrome
    depends_on:
      bot_test_chrome:
        condition: service_healthy
  bot_test_chrome:
    image: selenium/standalone-chrome
    container_name: bot_test_chrome
    ports:
      - "4445:4444"
      - "7999:7900"
      - "9222:9222"
    environment:
      - SE_NODE_MAX_SESSIONS=1  # Limita sesiones máximas
      - SE_NODE_SESSION_TIMEOUT=60  # Timeout en segundos
      - SE_SCREEN_WIDTH=800
      - SE_SCREEN_HEIGHT=600  # Resolución más baja = menos memoria
      - NOVNC_ENABLE_CLIPBOARD=true
      - VNC_CLIPBOARD_LIMIT=2097152  # Reducido a 2MB (de 10MB original)
    restart: always
