version: '3.8'

services:
  bot_gestorcali1:
    build:
      context: .
    container_name: bot_gestorcali1
    volumes:
      - ./app:/app
      - /home/Bot_Server/DBGestionBot:/DBGestionBot
    environment:
      - BOT_NAME=Bot_GestorCali1
      - CHROME_PORT=4445
      - CHROME_HOST=bot_gestorcali1_chrome
  bot_gestorcali1_chrome:
    image: selenium/standalone-chrome
    container_name: bot_gestorcali1_chrome
    ports:
      - "4445:4444"
      - "7900:7900"
      - "9222:9222"
    environment:
      - SE_VNC_NO_PASSWORD=1
    restart: always
