version: '3.8'

services:
  bot_gestorcali2:
    build:
      context: .
    container_name: bot_gestorcali2
    volumes:
      - ./app:/app
    environment:
      - BOT_NAME=Bot_GestorCali2
      - CHROME_PORT=4445
      - CHROME_HOST=bot_gestorcali2_chrome
  bot_gestorcali2_chrome:
    image: selenium/standalone-chrome
    container_name: bot_gestorcali2_chrome
    ports:
      - "4445:4444"
      - "7900:7900"
      - "9222:9222"
    environment:
      - SE_VNC_NO_PASSWORD=1
    restart: always
