version: '3.8'

services:
  bot_gestor1:
    build:
      context: .
    container_name: bot_gestor1
    volumes:
      - ./app:/app
    environment:
      - BOT_NAME=Bot_Gestor1
      - CHROME_PORT=4445
      - CHROME_HOST=bot_gestor1_chrome
  bot_gestor1_chrome:
    image: selenium/standalone-chrome
    container_name: bot_gestor1_chrome
    ports:
      - "4445:4444"
      - "7900:7900"
      - "9222:9222"
    environment:
      - SE_VNC_NO_PASSWORD=1
    restart: always
  bot_gestor2:
    build:
      context: .
    container_name: bot_gestor2
    volumes:
      - ./app:/app
    environment:
      - BOT_NAME=Bot_Gestor2
      - CHROME_PORT=4446
      - CHROME_HOST=bot_gestor2_chrome
  bot_gestor2_chrome:
    image: selenium/standalone-chrome
    container_name: bot_gestor2_chrome
    ports:
      - "4446:4444"
      - "7901:7900"
      - "9223:9222"
    environment:
      - SE_VNC_NO_PASSWORD=1
    restart: always
  bot_gestor3:
    build:
      context: .
    container_name: bot_gestor3
    volumes:
      - ./app:/app
    environment:
      - BOT_NAME=Bot_Gestor3
      - CHROME_PORT=4447
      - CHROME_HOST=bot_gestor3_chrome
  bot_gestor3_chrome:
    image: selenium/standalone-chrome
    container_name: bot_gestor3_chrome
    ports:
      - "4447:4444"
      - "7902:7900"
      - "9224:9222"
    environment:
      - SE_VNC_NO_PASSWORD=1
    restart: always
  bot_gestor4:
    build:
      context: .
    container_name: bot_gestor4
    volumes:
      - ./app:/app
    environment:
      - BOT_NAME=Bot_Gestor4
      - CHROME_PORT=4448
      - CHROME_HOST=bot_gestor4_chrome
  bot_gestor4_chrome:
    image: selenium/standalone-chrome
    container_name: bot_gestor4_chrome
    ports:
      - "4448:4444"
      - "7903:7900"
      - "9225:9222"
    environment:
      - SE_VNC_NO_PASSWORD=1
    restart: always
  bot_gestor5:
    build:
      context: .
    container_name: bot_gestor5
    volumes:
      - ./app:/app
    environment:
      - BOT_NAME=Bot_Gestor5
      - CHROME_PORT=4449
      - CHROME_HOST=bot_gestor5_chrome
  bot_gestor5_chrome:
    image: selenium/standalone-chrome
    container_name: bot_gestor5_chrome
    ports:
      - "4449:4444"
      - "7904:7900"
      - "9226:9222"
    environment:
      - SE_VNC_NO_PASSWORD=1
    restart: always
  bot_marcador2:
    build:
      context: .
    container_name: bot_marcador2
    volumes:
      - ./app:/app
    environment:
      - BOT_NAME=Bot_Marcador2
      - CHROME_PORT=4450
      - CHROME_HOST=bot_marcador2_chrome
  bot_marcador2_chrome:
    image: selenium/standalone-chrome
    container_name: bot_marcador2_chrome
    ports:
      - "4450:4444"
      - "7905:7900"
      - "9227:9222"
    environment:
      - SE_VNC_NO_PASSWORD=1
    restart: always
  bot_marcador3:
    build:
      context: .
    container_name: bot_marcador3
    volumes:
      - ./app:/app
    environment:
      - BOT_NAME=Bot_Marcador3
      - CHROME_PORT=4451
      - CHROME_HOST=bot_marcador3_chrome
  bot_marcador3_chrome:
    image: selenium/standalone-chrome
    container_name: bot_marcador3_chrome
    ports:
      - "4451:4444"
      - "7906:7900"
      - "9228:9222"
    environment:
      - SE_VNC_NO_PASSWORD=1
    restart: always
