name: Deploy

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v4

    - name: Deploy bots
      run: |
        set -e

        PROJECT_DIR="/home/Bot_Server/bot_server"

        echo "Deploy started"

        if [ ! -d "$PROJECT_DIR" ]; then
            mkdir -p $PROJECT_DIR
        fi

        cd $PROJECT_DIR

        git fetch origin || true
        git reset --hard origin/main || true

        chmod +x start_bots.sh

        bash start_bots.sh

        echo "Deploy finished"